os: osx
osx_image: xcode11.5
language: generic
before_script:
- brew update
- brew install --HEAD usbmuxd
- brew unlink usbmuxd
- brew link usbmuxd
- brew install --HEAD libimobiledevice
- brew install ideviceinstaller
- brew install ios-deploy
- git clone https://github.com/flutter/flutter.git -b beta --depth 1
script:
- flutter/bin/flutter build ios --release --no-codesign
cache:
  directories:
  - "$HOME/.pub-cache"
before_deploy:
- pushd build/ios/iphoneos
- mkdir Payload
- cd Payload
- ln -s ../Runner.app
- cd ..
- zip -r app.ipa Payload
- popd
deploy:
  provider: releases
  api_key:
    secure: j3mv/llT3Um++0iaUIbQCntQkT4x00WZm0FMwjs0+UKY0Ve5gaBYIwZRizsTvPy2rmqdGWq325kl0mKyTGbu8E32iA2u3KhpC7b7pN4tUWJEc0OQyy7/VbL7bMSK3eYL/eTCaPDzGxn/5ApF0YEG8Y0hMMdltGYriz9Z0ogKEQQtyHU9EoZOUezelfRoeA1xd59fDQbah22ssJaOLvzN++IaUa3lh1skYDWH5CJXREgiIz5K+pPGDSGRWgx7/YVplF69lLM2Iif+cAcfz4e+/iwd+XJ91FDrT7PeUQcAYawtJi9DmWBSthfe0ufhKJgwmhXOVxwJN1QHDJmc83Bk7HNuE7qDvRlmPBHc4J5eEA/TEj8IfHp2rWqOslEfnrGdaef8P3tSr6wjCrpNAMzxIlOs3JhaNkZ+KtNcG9jKV9v6B7aWNovFmMgjtsOacxq3U3+khGg8HdLzavZXLVRln6tB6RIELX57s7gNj7QdCQ5Q9OLXYDVs/q1aMYedqr/Whitx6o3MggsB10azXd9SlaOAfx0WrYqsBg+R7XOT8GLYEcnYQYINX8pgjyZGKl8o9ryKXezNAwgy+UcbHc98skFAlEgVorV/kMA/nnk/0ZkrTaJPffCCSRY1OIhv85pbB1WT4aGgBVheLXyPz20KNq8X/oep2sRy/lod58l9wRA=
  file: build/ios/iphoneos/app.ipa
  on:
    repo: bdragan19/atlantic_flutter
  skip_cleanup: 'true'
